### ISSUE TITLE
Loading Type and Loading Time not show in RUM

### ISSUE THREAD

**Issue by addhayam** [GetDutchie/datadog_flutter#104]
I followed the example, but the Loading Type and Loading Time do not display in RUM.
I found that it sometimes shows only on Android in main activities.
Please suggest.
<img width="871" alt="image" src="https://user-images.githubusercontent.com/92152431/167532262-ab55c162-d560-437e-b529-62d20bf27d9f.png">

**Comment by tshedor** [comment]
Hey @addhayam a PR would be really appreciated to add this feature.

**Comment by charafau** [comment]
Is this Andoird only or iOS too ?

**Comment by addhayam** [comment]
@tshedor Wow. Thank you so much. Do you have a rough plan for the release date?
@charafau  Both Android and iOS. But Loading Time for mainActivity shows up only on Android.

**Comment by addhayam** [comment]
@tshedor Sorry, I'm too new for the git community. So, Data Dog team has no plan to implement this on Flutter, right?

**Comment by tshedor** [comment]
@addhayam / @jeenDzul sorry, I have no plan to address this. I would recommend that you use [the official Datadog SDK](https://pub.dev/packages/datadog_flutter_plugin) instead per #108 . Their SDK has a rewritten HTTP client that should handle this resource tracking.
