### ISSUE TITLE
Question: How to use DatadogTracingHttpClient with GetConnect

### ISSUE THREAD

**Issue by rupas385** [GetDutchie/datadog_flutter#52]
Hi,

In my company we are using Get --> https://pub.dev/packages/get 

This packages have a component called GetConnect, and he is the component are in my project for handle request.

Now I am integrating datadog and all works fine, but need http tracing, but I am not sure if this package can works with GetConnect, please can help me?

Thanks

**Comment by tshedor** [comment]
Hey @rupas385 I tried to go down this road with #47 but to be honest I shouldn't have. These aren't packages that subscribe to Dart's [proscribed way of composing HTTP clients](https://github.com/dart-lang/http#using) and I can't speak to or support packages I don't maintain. I'd recommend opening a ticket with Get that requests how to compose an HTTP client or use Dart's native HTTP client instead (which is really very good on its own).
