### ISSUE TITLE
Invalid kind enum

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [GetDutchie/datadog_flutter#66]
While not getting response regarding this bug: https://github.com/GetDutchie/datadog_flutter/issues/64 I had to dig deeper into datadog java code regarding this error:

![image](https://user-images.githubusercontent.com/3918999/150128791-568b5268-f856-409b-bc4b-4726437c2481.png)

It appears that Enums that you are using in stopResoureceLoading are lowercased and in datadog java sdk all enums are uppercased: https://github.com/DataDog/dd-sdk-android/blob/2b9d9cce4d3e557bcf2881ae3613668923bcb7e1/dd-sdk-android/apiSurface (search for enum com.datadog.android.rum.RumResourceKind)
When added upercase FETCH problem was gone. 
Please update default value and documentation

**Comment by tshedor** [comment]
PRs are open!

**Comment by tshedor** [comment]
Being addressed in #69
