### ISSUE TITLE
Kotlin version mismatch due to a Flutter 2.10.0 breaking change

### ISSUE THREAD

**Issue by eerive** [GetDutchie/datadog_flutter#68]
**Case**
In our project, this plugin throws an error that the Kotlin version is mismatched. This is likely due to a [breaking change ](https://docs.flutter.dev/release/breaking-changes/kotlin-version) in the Flutter SDK, in which a version bump is required. Our project targets the sdkVersion 31.

**Reproduce steps**
To reproduce, run `flutter upgrade` in the stable branch and upgrade to 2.10.0. Then, try to build the app. 

**Expected behavior**
It should throw multiple errors in which building failed due to classes compiling with the wrong version.  

**Possible Fix**
This is temporarily fixed by changing the `ext.kotlin_version` to `1.6.10` (according to the breaking change page, it should working starting version `+1.5.13`).

**Comment by tshedor** [comment]
Good catch @eerive .

This is perhaps a stupid question, but is there a way to set a minimum number in gradle instead of this fixed version?

**Comment by eerive** [comment]
Yes, there is a way to include a dynamic version, as see in https://stackoverflow.com/questions/56961961/what-does-ext-kotlin-version-mean-in-build-gradle ; but it is not recommended to use it as sometimes builds can fail. It's annoying to single-handedly change it, but it seems to be the "safest" way to do so.

**Comment by tshedor** [comment]
@eerive eh, yeah I don't love that because we need the minimum patch number too according to the Flutter docs. However, it looks like `1.6` is available, so `1.6.+` would work here. If you can, could you please try out this branch with your app?

```yaml
# in your pubspec.yaml
datadog_flutter:
  git:
    url: git@github.com:GetDutchie/datadog_flutter.git
    ref: update-kotlin-version
```

**Comment by eerive** [comment]
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.6.+.
     Required by:
         project :app > project :datadog_flutter
      > Failed to list versions for org.jetbrains.kotlin:kotlin-stdlib-jdk7.
         > Unable to load Maven meta-data from [https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-jdk7/maven-metadata.xml]().
            > Could not get resource '[https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-jdk7/maven-metadata.xml]()'.
               > Could not GET '[https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-jdk7/maven-metadata.xml]()'.
                  > Connect to jcenter.bintray.com:443 [jcenter.bintray.com[/34.95.74.180]()] failed: Read timed out
```
                  
 Seems like the version thingy does not work like this - at least not for me.  @tshedor

**Comment by eerive** [comment]
I can report that the Datadog logs are working as intended after testing.
#70 looks good to me.
 @tshedor

**Comment by tshedor** [comment]
Great, thanks @eerive
