### ISSUE TITLE
Problem with the new version 1.4.1

### ISSUE THREAD

**Issue by MayuriXx** [GetDutchie/datadog_flutter#71]
Hi,

In the new version, my CI saying :

`e: /opt/hostedtoolcache/flutter/2.8.1-stable/x64/.pub-cache/hosted/pub.dartlang.org/datadog_flutter-1.4.1/android/src/main/kotlin/com/greenbits/datadog_flutter/DatadogFlutterPlugin.kt: (200, 69): Unresolved reference: uppercase`

Do you know why ?
waiting for, I set in my pub the 1.4.0 and it's good

Thank you and have a nice day 😬

**Comment by tshedor** [comment]
@MayuriXx could you please check your `build.gradle` and ensure your `ext.kotlin_version` is `1.5` or greater?

**Comment by MayuriXx** [comment]
I will check it tomorrow. Thank you! 😊

**Comment by MayuriXx** [comment]
yes it's good; 
I changed ext.kotlin_version in 1.6.10. 
Thank you ! 😊
