### ISSUE TITLE
No rum data uploaded - "(rum) No upload"

### ISSUE THREAD

**Issue by opsb** [GetDutchie/datadog_flutter#75]
I've had the logging working for a while but decided to add RUM for error tracking. No matter what I try though I always get the message `(rum) No upload`. 

```dart
  await DatadogFlutter.initialize(
    trackingConsent: TrackingConsent.granted,
    clientToken: const String.fromEnvironment("DD_TOKEN"),
    iosRumApplicationId:
        const String.fromEnvironment("DD_IOS_RUM_APPLICATION_ID"),
    serviceName: 'app-name',
    environment: "production",
    useEUEndpoints: true,
  );
  await DatadogFlutter.setUserInfo(id: "anon1");
  await DatadogRum.instance.addUserAction("hello");
```

Am I correct in thinking that the above should cause the user action to be sent with the next RUM data batch upload? (DD_TOKEN is my main client_token, I also tried the rum app client_token which again worked for logging but not RUM). Maybe I'm missing a step?

**Comment by tshedor** [comment]
Hey @opsb are you using `DatadogObserver`? RUM data sometimes doesn't upload if an active screen isn't set.

**Comment by tshedor** [comment]
And by sometimes I mean "maybe always?"

**Comment by opsb** [comment]
Hey @tshedor I'm not using the `DatadogObserver` at all actually, mainly because I don't use the MaterialApp navigation. Looks like I could get it working by just calling 
```
await DatadogRum.instance.startView(previousRouteName);
await DatadogRum.instance.startView(routeName);
```

I'll give it a go, thanks for the pointer!
