### ISSUE TITLE
extrainfo is not displayed in session's attributes

### ISSUE THREAD

**Issue by antonkad** [GetDutchie/datadog_flutter#76]
Hello, while trying to do: 

```
 await DatadogFlutter.setUserInfo(
        id: '42',
        name: 'John',
        extraInfo: {'surname': 'Doe'});
  },
```

On datadog, I cannot manage to find any extra info in the attributes of the the session, neither in the user part, neither in the json. The id and the name are properly displayed.

In the application settings, the app is of type javascript, I already tried the other types out of curiosity.

Regards

**Comment by tshedor** [comment]
Hey @antonkad what platform are you using? Flutter Android, Flutter Web, Flutter iOS?

**Comment by antonkad** [comment]
we are using mainly Flutter Web

**Comment by antonkad** [comment]
Hello, 

We've tried this new branch, btw if someone else passes here, in the url it's a ":" not a "/" such has in here:

`url: git@github.com:GetDutchie/datadog_flutter.git
`
So after trying this out, we are facing another kind of problem related to the plateform:

`UnsupportedError (Unsupported operation: Platform._operatingSystem)
`

In fact, when putting a break point, we can see that it tries to see if the plateform is iOS:

```
static Future<void> setUserInfo({
    String? id,
    String? email,
    Map<String, dynamic>? extraInfo,
    String? name,
  }) async {
    return await channel.invokeMethod('setUserInfo', {
      'id': id,
      'email': email,
      'extraInfo': Platform.isIOS ? jsonEncode(extraInfo) : extraInfo,
      'name': name,
    });
  }
```

https://github.com/GetDutchie/datadog_flutter/blob/main/lib/datadog_flutter.dart#L55

So we can't go thurther because of this erreur.

Regards

**Comment by antonkad** [comment]
We tried out the new version, the bug disapeared, but we no longer have any informations releated to the user (no user name, no user id). Neither in the user details, neither in the json attributes.

Do you know if there's a way to check the data that is sent, through a debugger localy ?

**Comment by tshedor** [comment]
So I guess, please comment out that `datadog_flutter` in your pubspec, save, and uncomment and make sure the SHA in your pubspec.lock reflects the new commit and give that another go please.

**Comment by tshedor** [comment]
Great, glad to hear it
