### ISSUE TITLE
Bug in Datadog Observer implementation

### ISSUE THREAD

**Issue by karthik-js** [GetDutchie/datadog_flutter#79]
The current implementation of `didPop` takes`current route` that is being popped as `newRoute` and `route` that is coming into the view after didPop is considered as `previousRoute`. 

This implementation is wrong. The correct way is that we have to switch the way we are `currentRoute` is fetched in `didPop`

**Comment by tshedor** [comment]
Hey @karthik-js PRs are open. I've not had a problem with this.

**Comment by karthik-js** [comment]
@tshedor I have observed this problem last week while I was integrating datadog into our app where the API calls of the newly popped screen are logged into the previous one. Can you point me to the PR that is open for this issue, If possible?

**Comment by tshedor** [comment]
@karthik-js there's no active PR for this issue, but you're welcome to submit one
