### ISSUE TITLE
Android API 31 Crash

### ISSUE THREAD

**Issue by masterwok** [GetDutchie/datadog_flutter#85]
When trying to run this package on Android API 31 and above a crash occurs. This is caused by an issue internal to the Datadog SDK: [https://github.com/DataDog/dd-sdk-android/issues/709](https://github.com/DataDog/dd-sdk-android/issues/709).

This issue should be resolved by bumping `com.datadoghq:dd-sdk-android` from version `1.8.1` to `1.11.1`.

**Comment by tshedor** [comment]
Released in 1.7.0; thanks @masterwok
