### ISSUE TITLE
Odd mappings of log levels happening on Android

### ISSUE THREAD

**Issue by btrautmann** [GetDutchie/datadog_flutter#91]
Hi there! We're working on integrating this flutter plugin into our codebase and noticing an oddity around Android's log levels once logs land in the datadog backend.

In short, all of our `info` logs are being mapped to `debug`. I first confirmed that we are definitely logging them as `info` to the public `log` function of the dart API, and then isolated the problematic mapping to [these lines](https://github.com/GetDutchie/datadog_flutter/blob/main/android/src/main/kotlin/com/greenbits/datadog_flutter/DatadogFlutterPlugin.kt#L117-L137) in the Android side of the plugin. It looks like `debug` is being mapped to `verbose`, `info` is being mapped to `debug`, and `notice` is being mapped to `info`.

Additionally, on the dart side within [`datadog_logger`](https://github.com/GetDutchie/datadog_flutter/blob/main/lib/datadog_logger.dart#L90-L101), passing `Level.INFO` would interestingly get mapped to `notice` based on its value, so we were downgrading our `Level.INFO` priorities to `Level.CONFIG` to fall into the `info` bucket, but now we realize this won't work because `info` is being mapped to `debug` on the Android side.

We confirmed that everything works as expected on iOS, assuming we do the downgrading to `Level.CONFIG` mentioned above. [Here's where iOS correctly maps the value sent by `dart` to the native SDK methods](https://github.com/GetDutchie/datadog_flutter/blob/main/ios/Classes/SwiftDatadogFlutterPlugin.swift#L51).

So we are hoping to bring clarity to two things:

1. Hopefully clean up the mapping on the dart side within the `_levelAsStatus` function to correctly map `Level.INFO` to `info`
2. Fix the mapping on the Android side of the plugin

This should bring both platforms to parity, though this may be a breaking change if anybody has done the same type of downgrading we were planning on doing in their implementations.

We'd be happy to open a PR up for this, but wanted to ensure this was indeed a bug prior to doing so.

**Comment by tshedor** [comment]
Hey @btrautmann there's no explicit decision for the mappings short of "I thought this was the most accurate." Based on the reactions to your issue, it sounds like this is a problem for others. I'd really appreciate a PR to correct the mappings to what it should be.

**Comment by tshedor** [comment]
@btrautmann thank you again for your work here and your unit testing. It's really helpful to me.

Your changes have been released as part of `2.0.0-beta.1`
