### ISSUE TITLE
Question: Why is tracing limited to http.Request

### ISSUE THREAD

**Issue by QuirijnGB** [GetDutchie/datadog_flutter#93]
Hello!

Before i go down a rabbit hole...
Why is it that the `DatadogTracingHttpClient` only decorates `http.Request`?
https://github.com/GetDutchie/datadog_flutter/blob/main/lib/datadog_tracing.dart#L22

All my requests seem to be `http.StreamedResponse` and therefore ignored.

Removing that statement seems to work for my use case

Thanks!

**Comment by tshedor** [comment]
Hey @QuirijnGB all methods in the HTTP client invoke `send` and receive a [StreamedResponse](https://github.com/GetDutchie/datadog_flutter/blob/main/lib/datadog_tracing.dart#L35). You shouldn't be sending a streamed response as a request. 

Could you provide some sample code that illustrates how you're using the HTTP client?

**Comment by QuirijnGB** [comment]
Hey @tshedor, sorry I meant StreamedRequest 😅.

I think rather than filtering out http.Request it should be http.Baserequest

Cheers

**Comment by tshedor** [comment]
Hey @QuirijnGB it is [BaseRequest already](https://github.com/GetDutchie/datadog_flutter/blob/main/lib/datadog_tracing.dart#L21)

**Comment by QuirijnGB** [comment]
Correct, but the [next line](https://github.com/GetDutchie/datadog_flutter/blob/main/lib/datadog_tracing.dart#L22)
seemingly filters out anything that's not a `http.Request`

**Comment by tshedor** [comment]
@QuirijnGB I guess that's a fair point. I thought `statusCode` was necessary through `http.Request`, but since that's the response, nevermind. Good catch.

**Comment by QuirijnGB** [comment]
Want me to write a PR for it?

**Comment by QuirijnGB** [comment]
Youre too quick https://github.com/GetDutchie/datadog_flutter/pull/94 :)

**Comment by tshedor** [comment]
@QuirijnGB released in 1.7.2
