### ISSUE TITLE
Disable [DEBUG] messages

### ISSUE THREAD

**Issue by Pitazzo** [GetDutchie/datadog_flutter#97]
Hi there,
first of all, kudos to you, awesome plugin. Till now we were using some bizarre custom endpoint in our backend logging to an InfluxDB instance, and the difference with Datadog is like night and day. 

I was wondering whether is possible to disable the printing of `[DATADOG SDK]` messages. If right now is not possible, including a `bool` field to the initializer params which enabled or disabled that logging would be great. We rely quite a lot on the console output in order to debug our app and these (a little bit verbose) messages make our traces difficult to read. Moreover, I'm getting tracing-related messages (`[DATADOG SDK] 🐶 → 18:46:53.725 [DEBUG] 💡 (tracing) No upload. Batch to upload: NO, System conditions: ✅`) although we are not using the tracing service. Is that normal? Thanks!

**Comment by tshedor** [comment]
Hey @Pitazzo unfortunately that comes from the Datadog SDK itself. I'd recommend opening your issue on the [Android](https://github.com/DataDog/dd-sdk-android) SDK or the [iOS](https://github.com/DataDog/dd-sdk-ios) SDK.
