### ISSUE TITLE
Random failure when logging

### ISSUE THREAD

**Issue by mrverdant13** [GetDutchie/datadog_flutter#98]
## Details

Hi!

I am facing a quite unexpected behaviour with the package.
Logging sometimes works, and some other times doesn't.

The message that is displayed when the log fails is this one: `failed because of a processing error or invalid data`.
I am only logging a simple `String` message, and I have also tried wrapping the `log` static method with a try catch without success.

Do you have any clue or suggestion on how to overcome this?

PS Thanks for the package!!!

**Comment by tshedor** [comment]
Hi @mrverdant13 I don't have an answer for that and haven't seen the message. Do you have a stack trace? Or an example log line that precedes the error messaging?

**Comment by mrverdant13** [comment]
I just found the root issue.

I am trying to switch environment by triggering DataDog initialization again.
Is there any way to do this?

In the meantime, I end up using a custom tag for my environment, but the client token cannot be changed.

**Comment by tshedor** [comment]
@mrverdant13 maybe I could understand your use case better. Why do you want to switch environments? Could you instead use separate Datadog loggers and add your unique tags to those individual loggers?

**Comment by tshedor** [comment]
@mrverdant13 heads up, I'm going to close this ticket in 72 hours
